name: NETCONF Deploy met local runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3


    - name: Install dependencies
      run: pip install -r netconf-hulk-requirements.txt

    - name: Run NETCONF script (PE/hulk-v2.py)
      run: python PE/hulk-v2.py
env:
  VROUTER_IP: ${{ secrets.VROUTER_IP }}
  VROUTER_USER: ${{ secrets.VROUTER_USER }}
  VROUTER_PASS: ${{ secrets.VROUTER_PASS }}
  LAB_ROUTER_IP: ${{ secrets.LAB_ROUTER_IP }}
  LAB_ROUTER_USER: ${{ secrets.LAB_ROUTER_USER }}
  LAB_ROUTER_PASS: ${{ secrets.LAB_ROUTER_PASS }}
  LAB_SWITCH_IP: ${{ secrets.LAB_SWITCH_IP }}
  LAB_SWITCH_USER: ${{ secrets.LAB_SWITCH_USER }}
  LAB_SWITCH_PASS: ${{ secrets.LAB_SWITCH_PASS }}